export const ROUTES = {
  HOME: "/",
  PRODUCT: "/product",
  ORDER: "/order",
  CART: "/cart",
  LOGIN: "/sign-in",
  REGISTER: "/sign-up",
  SHIPPING_ADDRESS: "/shipping-address",
  PAYMENT_METHOD: "/payment-method",
  PLACE_ORDER: "/place-order",
  PROFILE: "/user/profile",
  LIST_ORDER: "/user/orders",
  ADMIN_OVERVIEW: "/admin/overview",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_USERS: "/admin/users",
  ADMIN_ORDERS: "/admin/orders",
};
